export enum tagTypes {
  user = "user",
  service = "service",
  booking = "booking",
  validUser = "validUser",
  profile = "profile",
  category = "category",
  blogs = "blogs",
  questions = "questions",
  feedback = "feedback",
  faqs = "faqs",
  tutors = "tutors",

  faculty = "faculty",
  admin = "admin",
  student = "student",
  academicFaculty = "academic-faculty",
  academicDepartment = "academic-department",
  academicSemester = "academic-semester",
  building = "building",
  room = "room",
  course = "course",
  semesterRegistration = "semester-registration",
  offeredCourse = "offered-course",
  offeredCourseSection = "offered-course-section",
  offeredCourseSchedule = "offered-course-schedule",
  courseRegistration = "course-registration",
}

export const tagTypesList = [
  tagTypes.user,
  tagTypes.service,
  tagTypes.booking,
  tagTypes.validUser,
  tagTypes.profile,
  tagTypes.category,
  tagTypes.blogs,
  tagTypes.questions,
  tagTypes.feedback,
  tagTypes.admin,
  tagTypes.student,
  tagTypes.academicFaculty,
  tagTypes.academicDepartment,
  tagTypes.academicSemester,
  tagTypes.building,
  tagTypes.room,
  tagTypes.course,
  tagTypes.semesterRegistration,
  tagTypes.offeredCourse,
  tagTypes.offeredCourseSection,
  tagTypes.offeredCourseSchedule,
  tagTypes.courseRegistration,
];
